<?php $this->headScript()
	->appendFile('https://ajax.googleapis.com/ajax/libs/jquery/2.2.2/jquery.min.js')
	->appendFile($this->baseUrl('js/functions.js'))
	->captureStart() ?>


$(function()
{
	var actionUrl='<?= $this->url(array('controller' => 'staff', 'action' => 'validateedit',), 'default'); ?>';
	var formName='<?= $this->editform->getName() ?>';
	$(":input").on('blur', function(event) {
        var formElementId = $(this).attr('id');
        doValidation(formElementId, actionUrl, formName);
    });
});

<?php $this->headScript()->captureEnd() ?>

<div class="wrapper row2" style="padding: 80px;">
    <center> 
    <h1 class="wrapper2 row6">Modifica i dati </h1>
    <?= $this->editform; ?>
    </center>
</div>