<div class="pagMensili">
    <center> 
        <h1 class="titolo">Scegli un mese</h1>
    </center>

    <hr>
    <form id="miaForm" method="post" class="formFiltri" name="formMese" action="">
        <label class="formMese"><select id="selMese" name="mese" size="1">
                <option selected value="0"></option>
                <option value="1">Gennaio</option>
                <option value="2">Febbraio</option>
                <option value="3">Marzo</option>
                <option value="4">Aprile</option>
                <option value="5">Maggio</option>
                <option value="6">Giugno</option>
                <option value="7">Luglio</option>
                <option value="8">Agosto</option>
                <option value="9">Settembre</option>
                <option value="10">Ottobre</option>
                <option value="11">Novembre</option>
                <option value="12">Dicembre</option>
            </select><br>
        </label>
        <button style="margin-top: 20px; margin-bottom:20px;" type="submit">Visualizza</button>
    </form>
    <div class="mensile">
        <table border class="resMensile">
            <?php
            $mese = $this->mese;

            if (!is_null($mese)) {
                echo '<caption><b>Prenotazioni del mese di ' . $this->mese . '<b></caption>';
            } else {
                echo '<caption><b>Prenotazioni del mese di ' . $this->oggi . '<b></caption>';
            }
            $i = 0;
            $costoTot = 0;
            $durataTot = 0;
            ?>
            <tbody class="bodyMensile">
                <tr>
                    <th class = "tab5h"></th>
                    <th class = "tab5h">Id prenotazione</th>
                    <th class = "tab5h">Id utente</th>
                    <th class = "tab10h">Nome</th>
                    <th class = "tab10h">Cognome</th>
                    <th class = "tab15h">Marca</th>
                    <th class = "tab10h">Modello</th>
                    <th class = "tab10h">Targa</th>
                    <th class = "tab10h">Data inizio</th>
                    <th class = "tab10h">Durata</th>
                    <th class = "tab10h">Entrata</th>
                </tr>

                <?php foreach ($this->prenotazioni as $pren) : ?>
                    <?php
                    $auto = $this->product;
                    $i += 1;
                    $c = $i % 2;
                    $durata = $this->durata($pren->data_inizio, $pren->data_fine);
                    if ($c == 0) {
                        echo '<tr class="grigio"><th class="tab5h2">' . $i . '</th>';
                    } else {
                        echo '<tr><th class="tab5h">' . $i . '</th>';
                    }
                    echo '<td class="tab5">' . $pren->id_prenotazione . '</td>
                             <td class="tab5">' . $pren->id_utente . '</td>
                             <td class="tab10">' . $pren->nome . '</td>
                             <td class="tab10">' . $pren->cognome . '</td>
                             <td class="tab15">' . $pren->marca . '</td>
                             <td class="tab10">' . $pren->modello . '</td>
                             <td class="tab10">' . $pren->targa . '</td>
                             <td class="tab10">' . $pren->data_inizio . '</td>
                             <td class="tab10">' . $durata . ' giorni</td>
                             <td class="tab10">' . $this->prezzo($pren->costo) . '</td></tr>';
                    $costoTot += $pren->costo;
                    $durataTot += $durata;
                    ?>
                <?php endforeach; ?>
                <?php
                $entrate = $this->prezzo($costoTot);
                echo $this->RigheTot($i, 'Totale noleggi');
                echo $this->RigheTot($entrate, 'Entrate');
                echo $this->RigheTot($durataTot, 'Giorni prenotazione');
                ?>
            </tbody>
        </table>
    </div>
</div>