<div class="noPrenotazione">
    <div style="text-align: center; margin-top: 50px;">
        <p>Vuoi prenotare un'auto?</p>
        <p>Effettua il login o registrati</p>
    </div>
    <button style="width: 150px; height: 25px; position: relative; margin-left: 10px; float: left;" onclick="window.location.href = 'http:/TecnologieWeb/public/public/login'">Login</button>
    <button style="width: 150px; height: 25px; position: relative; margin-right: 10px; float: right;" onclick="window.location.href = 'http:/TecnologieWeb/public/public/register'">Registrati</button>
</div>