<?php
if ($this->pageCount > 1):?> 
    <div id="pagination" style="margin: 40px;">
    <?php echo $this->firstItemNumber; ?> - <?= $this->lastItemNumber; ?> di <?= $this->totalItemCount; ?> --- 


        <?php if (isset($this->previous)): ?>
            <a href="<?= $this->url(array('controller' => 'public', 'action' => 'catalog', 'pagina' => $this->first)); ?>">Inizio</a> | 
        <?php else: ?>
            Inizio | 
    <?php endif; ?>


        <?php if (isset($this->previous)): ?> 
            <a href="<?= $this->url(array('controller' => 'public', 'action' => 'catalog', 'pagina' => $this->previous)); ?>">&lt; Precedente</a> |
        <?php else: ?>
            &lt; Precedente |
    <?php endif; ?>


        <?php if (isset($this->next)): ?>
            <a href="<?= $this->url(array('controller' => 'public', 'action' => 'catalog', 'pagina' => $this->next)); ?>">Successivo &gt;</a> |
        <?php else: ?>
            Successivo &gt; |
    <?php endif; ?>


        <?php if (isset($this->next)): ?>
            <a href="<?= $this->url(array('controller' => 'public', 'action' => 'catalog', 'pagina' => $this->last)); ?>">Fine</a>
        <?php else: ?>
            Fine
    <?php endif; ?>

    </div>
<?php endif; ?>
