<div class="okPrenotazione">
    <div style="text-align: center; margin-top: 5px; margin-bottom: 100px;">
        <p>Prenota ora</p>

        <form>
            <label style="text-align: center;  height: 25px; position: relative; margin-left: 10px; float: left;">Data di inizio<input type="date" style="width: 150px;"name="dataInizio"></label>
            <label style="text-align: center; height: 25px; position: relative; margin-right: 10px;  float: right;">Data di fine<input type="date" style="width: 150px;"name="dataFine"></label>
        </form>
    </div>

    <button style="width: 150px; height: 25px; position: relative;" onclick="window.location.href = 'http:/TecnologieWeb/public/public/login'">Procedi</button>

</div>

