<div class="bgded overlay" style="background-image:url('http://localhost/TecnologieWeb/public/images/samples/parcoAuto.jpg'); padding-bottom:13%">
    <section id="pageintro" class="hoc clear">
        <div>
            <h4 class="heading">Scegli quella adatta a te</h4>
        </div>
    </section>
</div>

<div class="wrapper row2">

  <section class="hoc container clear">

    <h1 align="center"> ##########   ------   !CATALOGO AUTO!   ------   ########## </h1>

    <!-- ################################################################################################ -->
    <div class="clear"></div>
  </section>

  </div>
