<div class="bgded overlay" style="background-image:url('http://localhost/TecnologieWeb/public/images/samples/copertinaGrandTour.png'); padding-bottom:13%; height: 400px;">
    <section id="pageintro" class="hoc clear">
        <div>
            <h4 class="heading">Scegli quella adatta a te</h4>
        </div>
    </section>
</div>

<div id="pagina" style="text-align: center;">
    <div class="paginaCat">
        <div class="contenuto">
            <?php foreach ($this->products as $auto) : ?>
                <div class="prod">
                    <?php echo'<h1 class="title">' . $auto->marca . ':  ' . $auto->modello . '</h1>' ?>
                    <div class="image">
                        <?php echo '<img class="imagefrm" src="http://localhost/TecnologieWeb/public/images/catalog/' . $auto->immagine . '">' ?>
                    </div>

                    <?php
                    switch ($this->livello) {
                        case 'user':
                            echo '<div class = "okPrenotazione">';
                            echo '<div style = "text-align: center; margin-top: 5px;">';
                            echo '<p>Prenota ora</p>';
                            echo '<div><button style="margin-bottom: 30px;" onclick="window.location.href =\' ' . $this->url(array('controller' => 'user',
                                 'action' => 'preventivo',
                                 'idAuto' => $auto->id_auto,), 'default', true) . '\'">Procedi</button></div>';

                            /* <form method = "post" style = "height: 100px;">
                              <label style = "text-align: center;  height: 25px; position: relative; margin-left: 10px; float: left;">Data di inizio<input type = "date" style = "width: 150px;"name = "dataInizio"></label>
                              <label style = "text-align: center; height: 25px; position: relative; margin-right: 10px;  float: right;">Data di fine<input type = "date" style = "width: 150px;"name = "dataFine"></label>
                              <button type = "submit" style = "width: 150px; height: auto; position: absolute; margin-top: 60px; margin-left: 10px;">Verifica disponibilità</button>
                              </form>
                              </div>;*
                              $id = $auto->id_auto;
                              $in = $_POST['dataInizio'];
                              $fin = $_POST['dataFine'];
                              echo '<div>' . $in . '</div>';
                              echo '<div>' . $fin . '</div>';
                              echo '<div>' . $id . '</div>';*/

                              echo '</div>';
                              echo '</div>';
                            break;

                        case 'staff':
                            echo $this->render('public/_modifica.phtml');
                            break;

                        default:
                            echo $this->render('public/_noPrenotazione.phtml');
                            break;
                    }
                    //caso in cui non sia loggato
                    //echo $this->render('/public/_noPrenotazione.phtml'); 
                    //caso in cui sia registrato
                    //echo $this->render('public/_prenotazione.phtml');*/
                    ?>

                    <ul class="meta">
                        <?php echo '<li>prezzo: ' . $auto->prezzo . '</li>' ?>
                        <?php echo '<li>posti: ' . $auto->n_posti . '</li>' ?>
                        <?php echo '<li>segmento: ' . $auto->segmento . '</li>' ?>
                        <?php echo '<li>cilindrata: ' . $auto->cilindrata . '</li>' ?>
                        <?php echo '<li>potenza: ' . $auto->potenza . '</li>' ?>
                        <?php echo '<li>cavalli: ' . $auto->cavalli . '</li>' ?>
                        <?php echo '<li>alimentazione: ' . $auto->alimentazione . '</li>' ?>
                        <?php echo '<li>colore: ' . $auto->colore . '</li>' ?>
                        <?php echo '<li>targa: ' . $auto->targa . '</li>' ?>
                        <!--<li> <button onclick="window.location.href = 'http:/TecnologieWeb/public/public/register'">Registrati</button> </li>-->
                    </ul>
                </div>
            <?php endforeach; ?>

            <?php
            if ($this->products instanceof Zend_Paginator) { 
                echo $this->paginationControl($this->products, 'Sliding', 'public/_paginator.phtml');
            }
            ?>

        </div>
        <div class="sidebarFiltri">
            <h1 class="sidebarTitolo">Filtri</h1>
            <hr>
            <form id="miaForm" method="post" class="formFiltri" name="formFiltri" action="">
                <label class="formTitolo">Prezzo minimo <select id="selPrezzoMin" name="minimo" size="1">
                        <option selected value="0">Qualsiasi</option>
                        <option value="30">30€</option>
                        <option value="50">50€</option>
                        <option value="70">70€</option>
                        <option value="90">90€</option>
                        <option value="110">110€</option>
                        <option value="130">130€</option>
                    </select><br>
                </label>
                <label class="formTitolo">Prezzo massimo <select id="selPrezzoMax" name="massimo" size="1">
                        <option selected value="9999">Qualsiasi</option>
                        <option value="30">30€</option>
                        <option value="50">50€</option>
                        <option value="70">70€</option>
                        <option value="90">90€</option>
                        <option value="110">110€</option>
                        <option value="130">130€</option>
                    </select><br>
                </label>
                <label class="formTitolo">Numero posti <select id="selPosti" name="posti" size="1">
                        <option selected value="0">Qualsiasi</option>
                        <option value="2">almeno 2 posti</option>
                        <option value="3">almeno 3 posti</option>
                        <option value="4">almeno 4 posti</option>
                        <option value="5">almeno 5 posti</option>
                        <option value="6">almeno 6 posti</option>
                        <option value="7">almeno 7 posti</option>
                    </select>
                </label><br>
                <!--<input type="submit" value="Applica filtri" name="btnFiltra" style="margin-top: 10px; margin-bottom: 10px;"/>-->
                <!--
                $min = trim($_POST['minimo']);
                global $minimo;
                $minimo = $min;
                $max = trim($_POST['massimo']);
                $posti = trim($_POST['posti']);
                echo '<div>' . $minimo . '</div>';
                echo '<div>' . $max . '</div>';-->

                <button style="margin-top: 20px; margin-bottom:20px;" type="submit">Applica filtri</button>
                <!--
                
                if ($min!=0 || $max!=9999 || $posti!=0){
                    $query = '"location: http:/TecnologieWeb/public/public/catalog/minimo' . $min . '/massimo' . $max . '/posti' . $posti . '"';
                    header($query);
                }*/
                /*if($min!=0 || $max!=9999 || $posti!=0){
                    echo '<div><a style="margin-bottom: 30px;" href =\' ' . $this->url(array('controller' => 'public',
                    'action' => 'catalog',
                    'minimo' => $min,
                    'massimo' => $max,
                    'posti' => $posti), 'default', true) . '\'">Applica i filtri</a></div>';
                }-->
            </form>
        </div>
    </div>
</div>
