<div class="bgded overlay" style="background-image:url('http://localhost/TecnologieWeb/public/images/samples/teslawallpaper.jpg'); padding-bottom:13%">
    <section id="pageintro" class="hoc clear">
        <div>
            <h4 class="heading">Noleggia i tuoi sogni</h4>
            <p>Il più vasto parco d'auto d'europa</p>
        </div>
    </section>
</div>
<div class="wrapper row2">

  <section class="hoc container clear">
    <ul class="nospace group services">
      <li class="one_quarter first" >
        <article>
          <h6 class="heading font-x1"><a href="#">Chi siamo?</a></h6>
          <p>Studenti Progetto TWeb</p>
        </article>
      </li>
      <li class="one_quarter">
        <article>
          <h6 class="heading font-x1"><a href="#">La nostra missione</a></h6>
          <p>Sempre il progetto Tweb.</p>
        </article>
      </li>
      <li class="one_quarter">
        <article>
          <h6 class="heading font-x1"><a href="#">I nostri veicoli</a></h6>
          <p>I veicoli più all'avanguardia d'europa sono a tua disposizione.</p>
        </article>
      </li>
      <li class="one_quarter">
        <article>
          <h6 class="heading font-x1"><a href="#">F.A.Q.</a></h6>
          <p>Le Faq.</p>
        </article>
      </li>
    </ul>
    <div class="clear"></div>
  </section>

  </div>
