<?php echo '<div class="bgded overlay" style="background-image:' . $this->immagineBack("teslawallpaper.jpg") . ';padding-bottom:13%">' ?>
    <section id="pageintro" class="hoc clear">
        <div>
            <h4 class="heading">Noleggia i tuoi sogni</h4>
            <p>Il più vasto parco d'auto d'europa</p>
        </div>
    </section>
</div>
<div class="wrapper row2">

    <section class="hoc container clear">
        <ul class="nospace group services">
            <li class="one_quarter first" >
                <article style="height: auto;">
                    <h6 class="heading font-x1"><a href="#">Chi siamo?</a></h6>
                    <p>Siamo tre studenti che condividono una passione per le auto. Dopo anni di studi, impegno e dedizione, grazie a dei finanziatori che hanno riconosciuto in noi il nostro potenziale siamo riusciti ad arrivare dove siamo ora.</p>
                </article>
            </li>
            <li class="one_quarter">
                <article style="height: auto;">
                    <h6 class="heading font-x1"><a href="#">La nostra missione</a></h6>
                    <p>Vogliamo soddisfare i sogni dei miglior automobilisti che necessitano di un auto solo per un breve periodo di tempo e non vogliono acquistarne una.</p>
                </article>
            </li>
            <li class="one_quarter">
                <article style="height: auto;">
                    <h6 class="heading font-x1"><a href="#">I nostri veicoli</a></h6>
                    <p>Il nostro parco auto è il più vasto d'europa. Come avrete notato il nostro cavallo di battaglia è il lusso, ciò non toglie che anche le più comode e piccole auto possano essere noleggiate dal nostro catalogo che entro un anno conta di arrivare a più di 150 vetture noleggiabili!</p>
                </article>
            </li>
            <li class="one_quarter">
                <article style="height: auto;">
                    <h6 class="heading font-x1"><a href="<?=
                        $this->url(array(
                            'controller' => 'public',
                            'action' => 'FAQ'), 'default', true);
                        ?>">FAQ - Cliccami!</a></h6>
                                <h6 class="heading font-x1"><a href="documentazione_grp10.pdf">Documentazione del progetto</a></h6>
                </article>
            </li>
        </ul>
        <div class="clear"></div>
    </section>

</div>
