<footer id="footer" class="hoc clear">
    <div class="one_third first">
        <h6 class="heading">Informazioni</h6>
        <p>Programmatori del sito: Simone Cappella, Danilo Tomassini, Manuel Manelli. Studenti di Ingegneria Informatica all'universita Politecnica delle Marche.</p>
        
    </div>
    <div class="one_third">
        <h6 class="heading">Contattaci</h6>
        <ul class="nospace btmspace-30 linklist contact">
            <li><i class="fa fa-map-marker"></i>
                <address>
                     Via Lodovico Menicucci, 6, 60121 Ancona AN
                </address>
            </li>
            <li><i class="fa fa-phone"></i> +39 334 3245678</li>
            <li><i class="fa fa-fax"></i> +39 0724 2356789</li>
            <li><i class="fa fa-envelope-o"></i><a href="mailto:simone.cappella1997@gmail.com">simone.cappella1997@gmail.com</a></li>
            <li><i class="fa fa-envelope-o"></i><a href="mailto:manuelmanelli@live.it"> manuelmanelli@live.it</a></li>
            <li><i class="fa fa-envelope-o"></i><a href="mailto:danilo.tomassini.96@gmail.com" >danilo.tomassini.96@gmail.com</a></li>
        </ul>
        <ul class="faico clear">
            <li><a class="faicon-facebook" href="https://www.facebook.com/UNIVPM/"><i class="fa fa-facebook"></i></a></li>
            <li><a class="faicon-twitter" href="https://twitter.com/UnivPoliMarche?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor"><i class="fa fa-twitter"></i></a></li>
        </ul>
    </div>
    <div class="one_third">
        <h6 class="heading">Dove siamo</h6>
        <article>  <iframe width="320" height="140" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="http://maps.google.it/maps?f=q&amp;source=s_q&amp;hl=it&amp;geocode=&amp;q=Via+Brecce+Bianche,+12,+Ancona&amp;aq=0&amp;sll=41.442726,12.392578&amp;sspn=23.377375,53.657227&amp;ie=UTF8&amp;hq=&amp;hnear=Via+Brecce+Bianche,+12,+60131+Ancona,+Marche&amp;z=14&amp;ll=43.581248,13.515684&amp;output=embed"></iframe>
        </article>
    </div>
</footer>
