<footer id="footer" class="hoc clear">
    <!-- ################################################################################################ -->
    <div class="one_third first">
      <h6 class="heading">Informazioni</h6>
      <p>Primo paragrafo</p>
    </div>
    <div class="one_third">
      <h6 class="heading">Contattaci</h6>
      <ul class="nospace btmspace-30 linklist contact">
        <li><i class="fa fa-map-marker"></i>
          <address>
          Via &amp; Numero, Città, Codice Postale
          </address>
        </li>
        <li><i class="fa fa-phone"></i> +39 334 3245678</li>
        <li><i class="fa fa-fax"></i> +39 0724 2356789</li>
        <li><i class="fa fa-envelope-o"></i> progetto@tweb.com</li>
      </ul>
      <ul class="faico clear">
        <li><a class="faicon-facebook" href="#"><i class="fa fa-facebook"></i></a></li>
        <li><a class="faicon-twitter" href="#"><i class="fa fa-twitter"></i></a></li>
        <li><a class="faicon-dribble" href="#"><i class="fa fa-dribbble"></i></a></li>
        <li><a class="faicon-linkedin" href="#"><i class="fa fa-linkedin"></i></a></li>
        <li><a class="faicon-google-plus" href="#"><i class="fa fa-google-plus"></i></a></li>
        <li><a class="faicon-vk" href="#"><i class="fa fa-vk"></i></a></li>
      </ul>
    </div>
    <div class="one_third">
      <h6 class="heading">Dove siamo</h6>
      <article>  <iframe width="320" height="140" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="http://maps.google.it/maps?f=q&amp;source=s_q&amp;hl=it&amp;geocode=&amp;q=Via+Brecce+Bianche,+12,+Ancona&amp;aq=0&amp;sll=41.442726,12.392578&amp;sspn=23.377375,53.657227&amp;ie=UTF8&amp;hq=&amp;hnear=Via+Brecce+Bianche,+12,+60131+Ancona,+Marche&amp;z=14&amp;ll=43.581248,13.515684&amp;output=embed"></iframe>

        <h6 class="nospace font-x1"><a href="#">Roba</a></h6>
        <time class="font-xs block btmspace-10" datetime="2045-04-05">Luned', 5 Maggio 2019</time>
        <p class="nospace">Altra roba</p>
      </article>
    </div>
    <!-- ################################################################################################ -->
  </footer>
