<div class="wrapper row1" style="z-index: 2;">
    <header id="header" class="hoc clear">
        <div id="logo" class="fl_left">
            <h1><a href=" <?= $this->url(array(
                'controller' => 'public',
                'action' => 'index'),
                'default', true ); ?>"
                title="Izy Car Rent">Izy car rent</a></h1>
        </div>
        <nav id="mainav" class="fl_right">
            <ul class="clear">
                <li><a href=" <?= $this->url(array(
                            'controller' => 'public',
                            'action' => 'index'),
                            'default', true ); ?>"
                            title = "Home" >Home</a></li>
                <li><a href="<?= $this->url(array(
                            'controller' => 'public',
                            'action' => 'catalog'),
                            'default', true ); ?>"
                            title = "Catalogo" >Catalogo</a>
                </li>
                <li><a href="<?= $this->url(array(
                            'controller' => 'public',
                            'action' => 'profile'),
                            'default', true ); ?>"
                            title = "Profilo" >Profilo</a>
                </li>
                <li><a href="<?= $this->url(array(
                            'controller' => 'public',
                            'action' => 'register'),
                            'default', true ); ?>"
                            title = "Registrati" >Registrati</a>
                </li>
                <li><a href="<?= $this->url(array(
                            'controller' => 'public',
                            'action' => 'login'),
                            'default', true); ?>"
                            title = "Login" >Accedi</a>
                </li>
            </ul>
        </nav>
    </header>
</div>
