<div class="wrapper row1" style="z-index: 2;">
    <header id="header" class="hoc clear">
        <!-- ################################################################################################ -->
        <div id="logo" class="fl_left">
            <h1><a href="index.html">Izy car rent</a></h1>
        </div>
        <nav id="mainav" class="fl_right">
            <ul class="clear">
                <li class="active"><a href=" <?= $this->url(array(
                            'controller' => 'public',
                            'action' => 'index'),
                            'default', true ); ?>"
                                      title="Home">Home</a></li>
                <li><a class="drop" href="#">Catalogo</a>
                    <ul>
                        <li><a href="pages/gallery.html">Roba 1</a></li>
                        <li><a href="pages/full-width.html">Roba 2</a></li>
                        <li><a href="pages/sidebar-left.html">Roba 3</a></li>
                    </ul>
                </li>
                <li><a class="drop" href="#">Profilo</a>
                    <ul>
                        <li><a href="#">Roba 1</a></li>
                        <li><a class="drop" href="#">Roba 2</a>
                            <ul>
                                <li><a href="#">Roba 1</a></li>
                                <li><a href="#">Roba 2</a></li>
                                <li><a href="#">Roba 3</a></li>
                            </ul>
                        </li>
                        <li><a href="#">Roba 3</a></li>
                    </ul>
                </li>
                <li><a href="#">Registrati</a></li>
                <li><a href="#">Accedi</a></li>
            </ul>
        </nav>
        <!-- ################################################################################################ -->
    </header>
</div>
