<div class="wrapper row1" style="z-index: 2;">
    <header id="header" class="hoc clear">
        <div id="logo" class="fl_left">
            <h1><a href=" <?= $this->url(array(
                'controller' => 'public',
                'action' => 'index'),
                'default', true ); ?>"
                title="Izy Car Rent">Izy car rent</a></h1>
        </div>
        <nav id="mainav" class="fl_right">
            <ul class="clear">
                <li><a href=" <?= $this->url(array(
                            'controller' => 'staff',
                            'action' => 'index'),
                            'default', true ); ?>"
                            title = "Home" >Home</a></li>
                <li><a href="<?= $this->url(array(
                            'controller' => 'staff',
                            'action' => 'catalog'),
                            'default', true ); ?>"
                            title = "Catalogo" >Catalogo</a>
                </li>
                <li><a href="<?= $this->url(array(
                            'controller' => 'user',
                            'action' => 'profilo'),
                            'default', true ); ?>"
                            title = "Registrati" >Il mio profilo</a>
                </li>
                <li><a class="drop">Gestisci</a>
                    <ul>
                        <li><a class="drop">Auto</a>
                            <ul>
                                <li><a href=" <?= $this->url(array(
                                    'controller' => 'staff',
                                    'action' => 'inserisci'),
                                    'default', true ); ?>"
                                title ="Inserisci">Inserisci</a></li>
                                <li><a href=" <?= $this->url(array(
                                    'controller' => 'staff',
                                    'action' => 'modifica'),
                                    'default', true ); ?>"
                                title ="Modifica">Modifica</a></li>
                                <li><a href=" <?= $this->url(array(
                                    'controller' => 'staff',
                                    'action' => 'cancella'),
                                    'default', true ); ?>"
                                title ="Cancella">Cancella</a></li>     
                            </ul>
                        </li>
                        <li><a href=" <?= $this->url(array(
                                    'controller' => 'staff',
                                    'action' => 'visualizza'),
                                    'default', true ); ?>"
                                title ="Visualizza">Visualizza elenco</a></li>
                    </ul>
                    
                </li>
                <li><a href="<?= $this->url(array(
                            'controller' => 'staff',
                            'action' => 'logout'),
                            'default', true); ?>"
                            title = "Logout" >Logout</a>
                </li>
            </ul>
        </nav>
    </header>
</div>
 
