<?php echo $this->doctype() ?>
<html>
    <head>
      <?= $this->headMeta(); ?>
      <?= $this->headLink(); ?>
      <?= $this->headTitle(); ?>
    </head>
    <body id="top">
        <?= $this->render('_navbar.phtml'); ?>
        <div>
            <?php echo $this->layout()->content; ?>
        </div>
        <div class="wrapper row4 bgded overlay" style="background-image:url('images/demo/backgrounds/02.png');">
          <?= $this->render('_footer.phtml'); ?>
        </div>
        <div class="wrapper row5">
            <div id="copyright" class="hoc clear">
                <p class="fl_left">Copyright &copy; 2019 - All Rights Reserved - <a href="#">Domain Name</a></p>
            </div>
        </div>
        <a id="backtotop" href="#top"><i class="fa fa-chevron-up"></i></a>
        <!-- JAVASCRIPTS -->
        <script src="layout/scripts/jquery.min.js"></script>
        <script src="layout/scripts/jquery.backtotop.js"></script>
        <script src="layout/scripts/jquery.mobilemenu.js"></script>
    </body>
</html>
