<?php echo $this->doctype() ?>
<html>
    <head>
        <title>Title</title> 
        <meta charset="utf-8"> 
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"> 
        <link href="layout/styles/layout.css" rel="stylesheet" type="text/css" media="all">
    </head>
    <body id="top">
        <div class="bgded overlay" style="background-image:url('images/samples/teslawallpaper.jpg');"> 
            <!-- ################################################################################################ -->
            <div class="wrapper row1">
                <header id="header" class="hoc clear"> 
                    <!-- ################################################################################################ -->
                    <div id="logo" class="fl_left">
                        <h1><a href="index.html">Izy car rent</a></h1>
                    </div>
                    <nav id="mainav" class="fl_right">
                        <ul class="clear">
                            <li class="active"><a href="index.html">Home</a></li>
                            <li><a class="drop" href="#">Catalogo</a>
                                <ul>
                                    <li><a href="pages/gallery.html">Roba 1</a></li>
                                    <li><a href="pages/full-width.html">Roba 2</a></li>
                                    <li><a href="pages/sidebar-left.html">Roba 3</a></li>
                                </ul>
                            </li>
                            <li><a class="drop" href="#">Profilo</a>
                                <ul>
                                    <li><a href="#">Roba 1</a></li>
                                    <li><a class="drop" href="#">Roba 2</a>
                                        <ul>
                                            <li><a href="#">Roba 1</a></li>
                                            <li><a href="#">Roba 2</a></li>
                                            <li><a href="#">Roba 3</a></li>
                                        </ul>
                                    </li>
                                    <li><a href="#">Roba 3</a></li>
                                </ul>
                            </li>
                            <li><a href="#">Registrati</a></li>
                            <li><a href="#">Accedi</a></li>
                        </ul>
                    </nav>
                    <!-- ################################################################################################ -->
                </header>
            </div>
            <!-- ################################################################################################ -->
            <!-- ################################################################################################ -->
            <!-- ################################################################################################ -->
            <section id="pageintro" class="hoc clear">
                <div> 
                    <!-- ################################################################################################ -->
                    <h4 class="heading">Noleggia i tuoi sogni</h4>
                    <p>Il più vasto parco d'auto d'europa</p>
                    <!-- ################################################################################################ -->
                </div>
            </section>
            <!-- ################################################################################################ -->
        </div>
        <!-- End Top Background Image Wrapper -->
        <!-- ################################################################################################ -->
        <!-- ################################################################################################ -->
        <!-- ################################################################################################ -->
        <div class="wrapper row2">
            <?php echo $this->layout()->content; ?>
        </div>
        <!-- ################################################################################################ -->
        <!-- ################################################################################################ -->
        <div class="wrapper row4 bgded overlay" style="background-image:url('images/demo/backgrounds/02.png');">
            <footer id="footer" class="hoc clear"> 
                <!-- ################################################################################################ -->
                <div class="one_third first">
                    <h6 class="heading">Informazioni</h6>
                    <p>Primo paragrafo</p>
                </div>
                <div class="one_third">
                    <h6 class="heading">Contattaci</h6>
                    <ul class="nospace btmspace-30 linklist contact">
                        <li><i class="fa fa-map-marker"></i>
                            <address>
                                Street Name &amp; Number, Town, Postcode/Zip
                            </address>
                        </li>
                        <li><i class="fa fa-phone"></i> +00 (123) 456 7890</li>
                        <li><i class="fa fa-fax"></i> +00 (123) 456 7890</li>
                        <li><i class="fa fa-envelope-o"></i> info@domain.com</li>
                    </ul>
                    <ul class="faico clear">
                        <li><a class="faicon-facebook" href="#"><i class="fa fa-facebook"></i></a></li>
                        <li><a class="faicon-twitter" href="#"><i class="fa fa-twitter"></i></a></li>
                        <li><a class="faicon-dribble" href="#"><i class="fa fa-dribbble"></i></a></li>
                        <li><a class="faicon-linkedin" href="#"><i class="fa fa-linkedin"></i></a></li>
                        <li><a class="faicon-google-plus" href="#"><i class="fa fa-google-plus"></i></a></li>
                        <li><a class="faicon-vk" href="#"><i class="fa fa-vk"></i></a></li>
                    </ul>
                </div>
                <div class="one_third">
                    <h6 class="heading">Dove siamo</h6>
                    <article><a href="#"><img class="btmspace-15" src="images/demo/320x140.png" alt=""></a>
                        <h6 class="nospace font-x1"><a href="#">Roba</a></h6>
                        <time class="font-xs block btmspace-10" datetime="2045-04-05">Thursday, 5<sup>th</sup> April 2045</time>
                        <p class="nospace">Altra roba</p>
                    </article>
                </div>
                <!-- ################################################################################################ -->
            </footer>
        </div>
        <!-- ################################################################################################ -->
        <!-- ################################################################################################ -->
        <!-- ################################################################################################ -->
        <div class="wrapper row5">
            <div id="copyright" class="hoc clear"> 
                <!-- ################################################################################################ -->
                <p class="fl_left">Copyright &copy; 2019 - All Rights Reserved - <a href="#">Domain Name</a></p>
                <!-- ################################################################################################ -->
            </div>
        </div>
        <!-- ################################################################################################ -->
        <!-- ################################################################################################ -->
        <!-- ################################################################################################ -->
        <a id="backtotop" href="#top"><i class="fa fa-chevron-up"></i></a>
        <!-- JAVASCRIPTS -->
        <script src="layout/scripts/jquery.min.js"></script>
        <script src="layout/scripts/jquery.backtotop.js"></script>
        <script src="layout/scripts/jquery.mobilemenu.js"></script>
    </body>
</html>