<div class="bgded overlay" style="background-image:url('http://localhost/TecnologieWeb/public/images/samples/profilo.jpg'); background-position: center; background-position-y: 33%; height: 20em;">
    <section id="breadcrumb" class="hoc clear">
        <h6 class="heading">Il mio profilo</h6>
    </section>
</div>
<div class="wrapper row3">
    <main class="hoc container clear">
        <!-- main body -->
        <div class="sidebar one_quarter first">
            <img class="imgr borderedbox inspace-5" src="../images/demo/imgr.gif" alt="">
            <nav class="sdb_holder">
            </nav>
        </div>
        <div class="content three_quarter">
            <h1>Le mie informazioni</h1>
            <div id="comments">
                <form action="#" method="post">
                    <div class="one_third first">
                        <label for="name">Name <span>*</span></label>
                        <div style="border-style: solid;border-color: lightgray;border-width: thin;height: 3em;">
                            <div style=""> Prova </div>
                        </div>
                    </div>
                    <div class="one_third">
                        <label for="name">Name <span>*</span></label>
                        <div style="border-style: solid;border-color: lightgray;border-width: thin;height: 3em;">
                            <div style=""> Prova </div>
                        </div>
                    </div>
                    <div class="one_third">
                        <label for="name">Name <span>*</span></label>
                        <div style="border-style: solid;border-color: lightgray;border-width: thin;height: 3em;">
                            <div style=""> Prova </div>
                        </div>
                    </div>
                </form>
                <div style="border-style: solid;border-color: lightgray;border-width: thin;height: 3em;width: 10em;">
                    <div style="text-align: center;margin-top: 5%;color: #A2B70D;"> </div>
                </div>
            </div>
        </div>
        <div class="clear"></div>
    </main>
</div>
