<?php $this->headScript()
	->appendFile('https://ajax.googleapis.com/ajax/libs/jquery/2.2.2/jquery.min.js')
	->appendFile($this->baseUrl('js/functions.js'))
	->captureStart() ?>

  $(window).load(function() {
    $('#messaggi').scrollTop($('#messaggi')[0].scrollHeight - $('#messaggi')[0].clientHeight);
  });

  $(document).ready(function() {
      var $submit = $("input[type=submit]"),
          $inputs = $('input[type=text]');

      function checkEmpty() {

          // filter over the empty inputs

          return $inputs.filter(function() {
              return !$.trim(this.value);
          }).length === 0;
      }

      $inputs.on('blur', function() {
          $submit.prop("disabled", !checkEmpty());
      }).blur(); // trigger an initial blur
  });

<?php $this->headScript()->captureEnd() ?>
<div class="bgded overlay" style="background-image:url('http://localhost/TecnologieWeb/public/images/samples/faq.jpg'); background-position: center;">
  <!-- ################################################################################################ -->
  <section id="breadcrumb" class="hoc clear">
    <!-- ################################################################################################ -->
    <h6 class="heading">Messagga con l'amministratore</h6>
    <!-- ################################################################################################ -->
    <!-- ################################################################################################ -->
  </section>
  <!-- ################################################################################################ -->
</div>

<!-- End Top Background Image Wrapper -->
<!-- ################################################################################################ -->
<!-- ################################################################################################ -->
<!-- ################################################################################################ -->
<div class="wrapper row3">
  <main class="hoc container clear">
    <!-- main body -->
    <!-- ################################################################################################ -->
    <div class="content three_quarter">
      <div id="comments">
        <h2>Amministratore</h2>
        <div id="messaggi" style="overflow: auto;height: 40em;">
        <ul>
          <?php foreach ($this->messaggi as $messaggio) : ?>
          <li<?php if($messaggio->id_mittente == $this->user["id_utente"])
                      echo' class="senderm messageBorder"';
                   else
                   echo' class="receiverm messageBorder"';
              ?>>
            <article>
              <header>
                <?php
                      $timestamp = strtotime($messaggio->time_stamp);


                      echo date("d F Y H:i", $timestamp); ?>
              </header>
              <div class="comcont">
                <p><?= $messaggio->corpo ?></p>
              </div>
            </article>
          </li>
          <?php endforeach; ?>
        </ul>
      </div>
        <?php
          if(isset($this->user)){
              echo' <h2>Rispondi</h2>';
              echo $this->messageForm;
            }
        ?>
      </div>
      <!-- ################################################################################################ -->
    </div>
    <!-- ################################################################################################ -->
    <!-- / main body -->
    <div class="clear"></div>
  </main>
</div>
