<div class="bgded overlay" style="background-image:url('http://localhost/TecnologieWeb/public/images/samples/copertinaGrandTour.png'); padding-bottom:13%; height: 400px;">
    <section id="pageintro" class="hoc clear">
        <div>
            <h4 class="heading">Prenota in pochi click</h4>
        </div>
    </section>
</div>
<div class="paginaCat">

    <div class="prod">
        <h1 style="color: #A2B70D; text-align: center;">Prenotazione avvenuta con successo!!</h1>
        <div>
            <b style="color:#A2B70D;">Dettaglio prenotazione</b> 
            <?php
            foreach ($this->dataAuto as $auto){
            $inizio = $this->data_inizio;
            $fine = $this->data_fine;
            $ida = $this->id_auto;
            $idu = $this->id_utente;
            $prezzo = $auto->prezzo;
            $durata = $this->durata($inizio, $fine);
            echo '<p>Data di inizio: ' . $inizio . '</p>';
            echo '<p>Data di fine: ' . $fine . '</p>';
            echo '<p>Durata: ' . $durata . ' giorni</p>';
            echo $this->costo($prezzo, $durata);
            }
            ?>
        </div>
    </div>

</div>