<div class="bgded overlay" style="background-image:url('http://localhost/TecnologieWeb/public/images/samples/copertinaGrandTour.png'); padding-bottom:13%; height: 400px;">
    <section id="pageintro" class="hoc clear">
        <div>
            <h4 class="heading">Prenota in pochi click</h4>
        </div>
    </section>
</div>

<br /><br />
<div class="paginaCat">
    <p>Prenotazione avvenuta con successo</p>
    <div>
        riepilogo prenotazione 
        <?php
        $inizio = $this->data_inizio;
        $fine = $this->data_fine;
        $ida = $this->id_auto;
        $idu = $this->id_utente;
        echo '<p>' . $inizio . '</p>';
        echo '<p>' . $fine . '</p>';
        echo '<p>' . $ida . '</p>';
        echo '<p>' . $idu . '</p>';
        ?>
    </div>
</div>