<?php $this->headScript()
	->appendFile('https://ajax.googleapis.com/ajax/libs/jquery/2.2.2/jquery.min.js')
	->appendFile($this->baseUrl('js/functions.js'))
	->captureStart() ?>

  $(document).ready(function() {
      var $submit = $("input[type=submit]"),
          $inputs = $('#nome, #cognome, #username, #password');

      function checkEmpty() {
          return $inputs.filter(function() {
              return !$.trim(this.value);
          }).length === 0;
      }

      $inputs.on('blur', function() {
          $submit.prop("disabled", !checkEmpty());
      }).blur();
  });

<?php $this->headScript()->captureEnd() ?>
<div class="bgded overlay" style="background-image:url('http://localhost/TecnologieWeb/public/images/samples/faq.jpg'); background-position: center;">
    <!-- ################################################################################################ -->
    <!-- ################################################################################################ -->
    <!-- ################################################################################################ -->
    <!-- ################################################################################################ -->
    <section id="breadcrumb" class="hoc clear">
        <!-- ################################################################################################ -->
        <h6 class="heading">modifica staff</h6>
        <!-- ################################################################################################ -->
        <ul>
            <li><a href="<?=
                $this->url(array('controller' => 'admin',
                    'action' => 'staffmanager'), 'default', true)
                ?>">Torna a Gestisci staff</a></li>
            <li></li>
        </ul>
        <!-- ################################################################################################ -->
    </section>
    <!-- ################################################################################################ -->
</div>
<!-- End Top Background Image Wrapper -->
<!-- ################################################################################################ -->
<!-- ################################################################################################ -->
<!-- ################################################################################################ -->
<div class="wrapper row3">
    <main class="hoc container clear">
        <!-- main body -->
        <!-- ################################################################################################ -->
        <div class="content">
            <!-- ################################################################################################ -->
            <div id="comments">
                <h2>Modifica informazioni sul membro dello staff</h2>
                <ul>
                    <li>
                        <h2>Informazioni</h2>
                        <h2> <?= $this->form; ?> </h2>
                    </li>
                </ul>
            </div>
            <!-- ################################################################################################ -->
        </div>
        <!-- ################################################################################################ -->
        <!-- / main body -->
        <div class="clear"></div>
    </main>
</div>
