<?php echo '<div class="bgded overlay" style="background-image:' . $this->immagineBack("faq.jpg") . '; background-position: center;">'?>
  <section id="breadcrumb" class="hoc clear">
    <h6 class="heading">FAQ</h6>
    <ul>
      <li><a href="<?= $this->url(array('controller' => 'admin',
                                    'action' => 'managefaq'),
                                    'default', true)?>">Gestisci FAQ</a></li>
      <li></li>
    </ul>
  </section>
</div>
<div class="wrapper row3">
  <main class="hoc container clear">

    <div class="content">
      <div id="comments">
        <h2>Frequently Asked Questions</h2>
        <ul>
          <?php foreach ($this->products as $faq) : ?>
            <li>
              <article>
                <header>
                  <address>
                    <?php echo $faq->domanda ?>
                    <div style="text-align:right;">
                    <a href="<?= $this->url(array('controller' => 'admin',
		     										                      'action' => 'removefaq',
                                                  'faqid' => $faq->id_faq),
                                                  'default', true)?>"> <b> <?php echo $this->immaginiIcon("trash.png")?></b> </a>
                                                  &nbsp
                    <a href="<?= $this->url(array('controller' => 'admin',
                                                  'action' => 'editfaq',
                                                  'faqid' => $faq->id_faq),
                                                  'default', true)?>"> <b> <?php echo $this->immaginiIcon("edit.png")?></b> </a>
                    </div>
                  </address>
                  <?php echo $faq->time_stamp ?>
                </header>
                <div class="comcont">
                  <p><?php echo $faq->risposta ?></p>
                </div>
              </article>
            </li>
          <?php endforeach; ?>
          <li>
            <h2 style="text-align: center;">Aggiungi una nuova FAQ</h2>
              <?= $this->faqForm; ?>
          </li>
        </ul>
      </div>
      <!-- ################################################################################################ -->
    </div>
    <!-- ################################################################################################ -->
    <!-- / main body -->
    <div class="clear"></div>
  </main>
</div>
